#PREDICADOS
#   metodo - POST
#   path-/api/tasks
#   header - Content-Type = application/json
#   quando n corresponder ao predicado de duplicado

#RESPOSTA
#   statuscode - 201
#   header - Content-Type = application/json
#   location = /api/tasks/{id}
#   body - json com id
#          status = "created"

#TEST 
#post - title diferente de "duplicate"


POST http://localhost:2525/imposters
Content-Type: application/json

{
  "name": "Ex11",
  "port": 2121,
  "protocol": "http",
  "stubs": [
    {
      "responses": [
        {
          "is": {
            "statusCode": 201,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "duplicate_taks"
            }
          }
        }
      ],
      "predicates": [
        {
          "equals": {
            "path": "/api/tasks",
            "method": "POST"
          }
        },
        {
          "contains": {
            "body": {"title": "duplicate"}
          }
        }
      ]
    },
    {
      "responses": [
        {
          "is": {
            "statusCode": 201,
            "headers": {"Content-Type": "application/json"},
            "Location": "/api/tasks/123",
            "body": {
              "id": 123,
              "status":"created"
            }
          }
        }
      ],
      "predicates": [
        {
          "equals": {
            "path": "/api/tasks",
            "method": "POST",
            "headers": { "Content-Type": "application/json" }
          }
        }
      ]  
    }
  ]
}


### 

#teste com title "duplicate"
POST http://localhost:2121/api/tasks
Content-Type: application/json

{
  "title": "duplicate",
  "description": "task"
}


###

#post com title diferente de "duplicate"
POST http://localhost:2121/api/tasks
Content-Type: application/json

{
  "title": "yamaha",
  "description": "motas"
}